name: External Links Validator
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 12 * * 6'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Link Checker
      uses: peter-evans/link-checker@v1
      with:
        args: -v -r *
    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Link Checker Report
        content-filepath: ./link-checker/out.md
        labels: report, automated issue
