name: Internal Links Validator
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Validade internal links
        uses: nolte/github-action/markdown/validate@v0.1.0
        with:
          args: "--frail"
